### PR TITLE
Add atop property to ezText() method in Cezpdf class

### PR DESCRIPTION
**Pull request by chros73**
Add `atop` property to `ezText()` method in `Cezpdf` class, good for:
- aligning multiline text in footer

Usage:
`$this->ezText($footer,6,array('justification'=>'center','atop' => 44, 'aleft'=>50, 'aright'=>545.28));`

Closes: #74

### CODE REVIEW

**Comment by ole1986** [comment]
@chros73 thank you for the PR

shouldn't we use a function variable instead of adding a $this->top?
and recover the $this->y with it?

**Comment by ole1986** [comment]
Also we should think of what happens when the ezText([...]) containing the "atop" option reaches the end of page?!

**Comment by chros73** [comment]
Thanks for creating the example file and for your comments. I'll think about it and I'll get back to you.

**Comment by ole1986** [comment]
@chros73 Thank you - and do not get me wrong I like to have the atop as an option but we should aware such page breaks situations.

**Comment by ole1986** [comment]
Also, it looks like whenever I put **line breaks** into the ezText containing "atop" option the next ezText (without an atop option) will consume these line breaks too until its printed...

**Comment by ole1986** [comment]
just added a quick fix so atop works with paging.
But to not have side-effects of other ezTExt calls, it needs to be the last call of a page.

Which is not the smartest solution IMO

**Comment by chros73** [comment]
> and do not get me wrong - I would like to have 

Of course not! :) I thank you for thinking with me.
I'm just dealing with another production problems (not just one) at the moment.
I'll get back to you if I'll have more time.
Cheers

**Comment by chros73** [comment]
Hi!

First of all, sorry for the late reply.

> just added a quick fix so atop works with paging.
But to not have side-effects of other ezTExt calls, it needs to be the last call of a page.

I took a look at your mod:
- the original idea was/is that `atop` shouldn't modify the `y` value at all
  - so this way you don't have to keep track of it

I check the old code again, it was version `009e`. That time `addTextWrap` method was a standalone method, now it calls `addText`.

> whenever I put line breaks into the ezText containing `atop` option the next ezText (without an `atop` 
option) will consume these line breaks 

I could also reproduced this with my original suggestion.
I have played with it a day last week, and I couldn't fixed it: a new one always emerged.
So I just applied more line breaks to those places.

So, I'm closing this pull request, thanks for you time this time and all your effort made so far.

The original problem was this:
- how we can align (e.g. justify) multiline tesxt in the footer :)

**Pull request closed without merging**
